spring:
  application:
    name: PD_project
  datasource:
    url: jdbc:mysql://localhost:3306/doctor
    username: root
    password: 12022003b
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
#    lazy-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuandatt2003@gmail.com
    password: szcz gctp hskm wqql
    properties:
      mail:
        smtp:
          auth : true
          starttls:
            enable:  true

logging:
  level:
    root: WARN
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
          bind: TRACE

server:
  port: 8082
  servlet:
    context-path: "/api/v1"

jwt:
  signerKey: "xxiZx4S9K4jCse8UI89bTPGihA9MXjHSob+hfnckRMo7yRlIO7xheltlc/+dKFv4"



